repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: yapf-diff
        name: yapf-diff
        entry: ./yapf-diff-hook.sh
        language: system
