name: cellpose
channels:
  - pytorch
  - defaults
dependencies:
  - python==3.7
  - cudatoolkit=10.2
  - pytorch
  - numpy>=1.20.0
  - pip
  - pip:
    - PyQt5
    - PyQt5.sip
    - numba>=0.43.1
    - scipy
    - torch>=1.6
    - opencv-python-headless
    - pyqtgraph>=0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - tifffile
    - --editable ./
    - pytest
    
  
